### ISSUE TITLE
update node.js 12 to 16

### ISSUE THREAD

**Issue by motopods** [ilCollez/ssh-scp-deploy#15]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: ilCollez/ssh-scp-deploy@v1.1.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by ilCollez** [comment]
Thanks for the report, I'll migrate this action to Node 16 as soon as possible.

**Comment by ilCollez** [comment]
The action has been migrated to Node 16, please update your code to use ilCollez/ssh-scp-deploy@v1.2.0
