### ISSUE TITLE
[Feature request] add an option to handle dot file.

### ISSUE THREAD

**Issue by motopods** [ilCollez/ssh-scp-deploy#22]
Sometimes it's necessary to upload files that start with a dot, such as .env. Currently, these files are ignored. We hope to add a configuration to support dot files. For fast-glob, we could expose its dot parameter. Also, the clean shell script needs to be handled.

**Comment by motopods** [comment]
I think find ./*  should be replace to find . when the dot option is enabled.  Otherwise, dot files will be ignored.

**Comment by ilCollez** [comment]
Oh, okay. Don’t worry, I’ll release a fix for this in a few days :)

**Comment by ilCollez** [comment]
Hi! I released the fix with a bunch of minor updates in the `development` branch. Later this day i'll do some tests before merging everything into main. Meanwhile If you want, you can test the action and let me know :)

**Comment by ilCollez** [comment]
Hi @motopods ! I just release v1.3.0, which solves your problem. Please let me know if this new update addresses your issue :)

**Comment by motopods** [comment]
Nice job, thanks!
