### ISSUE TITLE
Bug: privateKeyPath option must not be specified when privateKey is specified.

### ISSUE THREAD

**Issue by Eslam-Gaber645** [ilCollez/ssh-scp-deploy#9]
I have this issue after updating node-ssh to v13.0.0.
![image](https://user-images.githubusercontent.com/89040792/182894256-1f3b91a8-2753-436a-98d3-559b4e7e14b8.png)

**Comment by ilCollez** [comment]
Thanks for the report. I'll fix it as soon as possible

**Comment by ilCollez** [comment]
it should be fixed now, let me know if you have any other problems

**Comment by Eslam-Gaber645** [comment]
> it should be fixed now, let me know if you have any other issues

It has been fixed, thank you.
